---
- name: Provision Ubuntu Controller
  hosts: localhost
  gather_facts: false
  remote_user: ubuntu
  vars_files:
    - ../secret.yml
  tasks:
  - name: Launch Base Ubuntu AMI
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "{{ target_aws_region }}"
      image: "{{ ctrl_ami }}"
      instance_type: "{{ ctrl_instance_type }}"
      zone: "{{ zone }}"
      group_id: [ "{{ sg_out.group_id }}" ]
      key_name: "{{ keyname }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 300
          delete_on_termination: true
      wait: yes
      wait_timeout: 500
      exact_count: "{{ count }}"
      count_tag:
        Name: Controller
      instance_tags:
        Name: "{{ customer }} - Controller"
        Role: "Controller"
        CustomerName: "{{ customer }}"
    register: ec2
  - debug: var=ec2

  - name: Add the newly created EC2 instance(s) to the local host group (located at ./inventory/hosts)
    lineinfile:
      dest: "inventory/hosts"
      regexp: "{{ item }}"
      insertafter: "[controllers]"
      line: "{{ item.public_ip }} ansible_user=ubuntu ansible_port=22"
    when: ec2|success
    with_items: ec2.instances

  - name: Wait for SSH to come up
    wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=500 state=started
    when: ec2|success
    with_items: ec2.instances
    register: sshup

  post_tasks:
  - debug: msg="Accessible link - http://{{ item.public_ip }}:8080"
    when: sshup|success
    with_items: "{{ ec2.instances }}"

